---
title: Venkat Ganesan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: ''
baseurl: ''
markdown: kramdown
permalink: "/writing/:title"
navigation:
- title: Home
  url: "/"
- title: Writing
  url: "/writing/"
- title: About
  url: "/about/"
sass:
  sass_dir: _sass
  style: :compressed
port: 8989
